spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update
# App Properties
app:
  jwtSecret: prod-secret-key
  jwtExpirationMs: 86400000
